# Used to generate the site
# Site settings
title: Liturgia
header-img: img/home-bg.jpg
email: thom@thomcrowe.com
description: "Living the Ancient Faith in the Modern World"
baseurl: ""
url: "http://liturgia.org"
itunes_url: "https://itunes.apple.com/us/podcast/xxx"
twitter_username: liturgia
github_username:  
facebook_username:  liturgia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
